### ISSUE TITLE
oscal-cli 0.3.2 throws exceptions during validation of SSP

### ISSUE THREAD

**Issue by volpet2014** [usnistgov/oscal-cli#109]
When running a validation on latest build of oscal-cli 0.3.2 of an SSP, it reports the validation errors but throws exception for every validation error found.  

Note: pulled latest version down from repo and rebuilt using "mvn install"

This occurs when running the following command:
oscal-cli ssp validate --as xml AwesomeCloudSSP1.xml 

This can be replicated by using the attached SSP sample.
See attached output captured (cli_error.out) in zip file

[cli_errors.zip](https://github.com/usnistgov/oscal-cli/files/10814230/cli_errors.zip)

**Comment by GaryGapinski** [comment]
Occurs with 0.3.3 as well.
macOS Ventura 13.2.1 MacBook Pro Intel hardware.
[cli.out.txt](https://github.com/usnistgov/oscal-cli/files/10814613/cli.out.txt)

**Comment by aj-stein-nist** [comment]
Thank you for your report. I know that exceptions maybe should not be logged, but this document doesn't have a schema validation error? It is calling out a `<description>This text is not properly wrapped in HTML tags like, p, h1, table, etc</description>` and I cannot find it quickly from skimming the document. I will need some time later today to re-review. I tried quick `grep`ing and will need to fire up Saxon/Oxygen for faster XPath queries to find it. I appreciate the sample, but it's large!

**Comment by volpet2014** [comment]
It does it anytime any error is thrown.  Even on small docs.  I can provide a smaller SSP if needed that has that error.

Sent from my iPhone

On Feb 23, 2023, at 9:52 AM, A.J. Stein ***@***.***> wrote:

﻿

Thank you for your report. I know that exceptions maybe should not be logged, but this document doesn't have a schema validation error? It is calling out a <description>This text is not properly wrapped in HTML tags like, p, h1, table, etc</description> and I cannot find it quickly from skimming the document. I will need some time later today to re-review. I tried quick greping and will need to fire up Saxon/Oxygen for faster XPath queries to find it. I appreciate the sample, but it's large!

**Comment by GaryGapinski** [comment]
There is something odd going on here (for which I do not yet have a reliable diagnosis).

I tried validating the document in OxygenXML. Failed.

I removed lines 2-5. Tried validation using (explicitly) https://raw.githubusercontent.com/usnistgov/OSCAL/v1.0.4/xml/schema/oscal_complete_schema.xsd. Failed, not because the document was bad, but "Failed to read schema document 'https://raw.githubusercontent.com/usnistgov/OSCAL/v1.0.4/xml/schema/oscal_complete_schema.xsd', because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not <xsd:schema>."

Tried using a local copy (explicitly) of `oscal_complete_schema.xsd`. Validation succeeded.

Then: I realized I had an active Zscaler VPN active. Got rid of it.

Tried a validation with an explicit remote schema. Worked (no thanks to Zscaler).

Added back lines 2-5. Tried a validation with an explicit remote schema. Failed.

Dropped line 5. Tried a validation with an explicit remote schema. Worked. Tried validation with xml-model schema. Worked. Restored line 5. Tried validation with remote XML Schema. Worked.

Restored line 5. Tried validation using remote schema. Worked. Tried validation using declared (xml-model) schemas. Worked.

Tried validation with `oscal-cli.` Failed noisily.

I'll have to try this when conditions are more clement. I might try an XML Catalog to remove any network-induced oddities.

**Comment by aj-stein-nist** [comment]
Interesting, I was trying to debug myself and experienced similarly odd issues myself with using the Schema via OxygenXML. We also have similar setups, Gary, because our VPN does set up proxy for TLS intercept, so I was curious if Oxygen with silently failing with cert issues (it appears to cache on remote HTTP queries from time to time, but it has been a while).

**Comment by GaryGapinski** [comment]
Note that line 5 of `AwesomeCloudSSP1.xml` is incorrect.
```xml
<?xml-model schematypens="http://purl.oclc.org/dsdl/schematron" title="FedRAMP SSP constraints" https://github.com/18F/fedramp-automation/raw/master/src/validations/rules/ssp.sch" phase="#ALL"?>
```
That is because [this](https://github.com/GSA/fedramp-automation/blob/43685accaef96434d9ff59c4236ba0d25302c961/src/validations/rules/sample-ssp.xsl#L155) is incorrect in more than one way. It is missing the `href="`; the schema location target is also incorrect.  See https://github.com/GSA/fedramp-automation/issues/387.

Line 5 of `AwesomeCloudSSP1.xml` should be
```xml
<?xml-model schematypens="http://purl.oclc.org/dsdl/schematron" title="FedRAMP SSP constraints" href="https://raw.githubusercontent.com/GSA/fedramp-automation/master/src/validations/rules/rev4/ssp.sch" phase="#ALL"?>
```
Line 4 should also be version 1.0.4 of the OSCAL XML Schema.
```xml
<?xml-model schematypens="http://www.w3.org/2001/XMLSchema" title="OSCAL complete schema" href="https://raw.githubusercontent.com/usnistgov/OSCAL/v1.0.4/xml/schema/oscal_complete_schema.xsd" ?>
```
When those lines are changed XML Schema and Schematron validations occur correctly in <oXygen/> XML Editor. There are 187 Schematron messages and **no** XML Schema messages.

`oscal-cli` remains noisy. Aside from the Java exception messages, there are spurious complaints about `<description/>` [sic] elements. These (empty `description` elements) are valid according to the OSCAL (v1.0.4) XML Schema, viz [`description`](https://github.com/usnistgov/OSCAL/blob/v1.0.4/xml/schema/oscal_complete_schema.xsd#L1088-L1102), [`markupMultilineType`](https://github.com/usnistgov/OSCAL/blob/v1.0.4/xml/schema/oscal_complete_schema.xsd#L8443-L8463).

**Comment by aj-stein-nist** [comment]
Thank you very much, I was trying to figure out what the deal was with that and missed it.

> When those lines are changed XML Schema and Schematron validations occur correctly in XML Editor. There are 187 Schematron messages and no XML Schema messages.

Thanks for pointing this out. I was scratching my head yesterday because even when I removed all the `xml-model` PIs and just on the CLI or with Oxygen's "Validate with ..." menu to do XSD validation without specifying the schema inline within the document, it validates. But @volpet2014 also admitted he suspects there may be missing tags in a `description`, weirdly, when I do try XPath searching I get odd behavior and results looking for `//description`, so I am increasingly impressed by the difficulty I have with the sample document. I like the challenge!

**Comment by volpet2014** [comment]
Good catch Gary.  I totally missed that href also.  The <description/> problem I solved by adding <p>blah blah blah</p> inside the <description>.

**Comment by GaryGapinski** [comment]
An empty `description` is perfectly valid. There are 10 `//description[. eq '']` in the sample document.

**Comment by aj-stein-nist** [comment]
> An empty `description` is perfectly valid. There are 10 `//description[. eq '']` in the sample document.

I have an embarrassing admission: the results were coming back as a bunch of whitespace in Oxygen, and weirdly, the description line is a white blank line and all the metadata about search results in the other columns was far too the right and there were a few examples as you said. So I thought I was not getting results back, oh I was! 🤦 

Now I guess I need to dig into how/why the `oscal-cli`, or more realistically liboscal-java, does what it does and why.

**Comment by aj-stein-nist** [comment]
Interesting, so `<description></description>` and `<description />` get handled differently and that's how I have never noticed this? 😆

**Comment by aj-stein-nist** [comment]
> Those are semantically identical.

Yes, this makes sense, but a brief period after editing, with `xml-model` PIs completely removed, switching it and playing around to set up Java debugging led to all 10 lighting up like a Christmas tree to say empty is not allowed, weirdly just like the `oscal-cli` and it's libraries, but I am not sure where that validation came from ...

**Comment by GaryGapinski** [comment]
I consider the OSCAL XML Schema normative and authoritative. Something must be incorrect in `oscal-cli`.

Not only `description` but `title` can be empty. The following has multiple XML Schema sins but line 5 has none. `title` must be present but need not have content.
```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model schematypens="http://www.w3.org/2001/XMLSchema" title="OSCAL complete schema" href="https://raw.githubusercontent.com/usnistgov/OSCAL/v1.0.4/xml/schema/oscal_complete_schema.xsd" ?>
<system-security-plan xmlns="http://csrc.nist.gov/ns/oscal/1.0" uuid="">
    <metadata>
        <title />
        <last-modified />
        <version />
        <oscal-version />
    </metadata>
</system-security-plan>
```

This is evocative of the 20th century (almost to the week) [song](https://en.wikipedia.org/wiki/Yes!_We_Have_No_Bananas) titled "Yes! We Have No Bananas".

**Comment by GaryGapinski** [comment]
The attached sample catalog demonstrates a very simple XML Catalog
and
a problem to be solved for references from within the Schematron to ancillary files.

The Schematron evaluation will fail because the catalog lacks `fedramp_values.xml`. This is in retrospect a bit of a design flaw having an adverse effect on XML Catalog. A simple fix would be to make `fedramp_values.xml` a sibling of ssp.sch in the repo as well as in any XML Catalog, rather than a residence several countries away ([`../../../content/rev4/resources/xml/fedramp_values.xml`](https://github.com/GSA/fedramp-automation/blob/master/src/validations/rules/rev4/ssp.sch#L275-L278)). The rev4/rev5 split complicates that as do baseline references ([`../../../../dist/content/rev4/baselines/xml/…`](https://github.com/GSA/fedramp-automation/blob/master/src/validations/rules/rev4/ssp.sch#L279-L282)).

`../anything` is a path to perdition.

[catalog.zip](https://github.com/usnistgov/oscal-cli/files/10827666/catalog.zip)

**Comment by GaryGapinski** [comment]
>so the point of your last message before this reply is we think the Schematron is to blame for these errors in oscal-cli per this bug report?

No. The spurious errors appear to be of `oscal-cli` origin — not Schematron and not OSCAL XML Schema (at least the OSCAL XML Schema from the OSCAL repo).

The original specimen OSCAL SSP document (`AwesomeCloudSSP1.xml`) had an error in the xml-model PI for a Schematron schema. If one simply removes that xml-model PI (by commenting out line 5), `oscal-cli` still produces errors for empty `description` elements and pairs each with a verbose exception stack. There are 10 such errors corresponding to the 10 empty `description` elements in the sample document.

When line 5 is removed _validation within OxygenXML_ finds no (OSCAL XML Schema) errors, but _validation with`oscal-cli`_ does (and adorns each with a verbose stack trace). Each finding by `oscal-cli` is erroneous (and it punctuates the validation with `$?=1`).

**Comment by aj-stein-nist** [comment]
OK, that I need to continue through and figure out this coming week then, thanks!

**Comment by GaryGapinski** [comment]
It's been many years since I had a tryst with Java and I am no longer adept. I do not know if Xerces supports embedded Schematron (`ssp.sch` is not involved with `oscal-cli` disliking empty `description` elements and neither is the OSCAL XML Schema). Something else is the origin of the dislike.

**Comment by GaryGapinski** [comment]
Another observation (I was too lazy to work with Xerces):
```
gapinski@flexion-mac-C02FCBVSMD6N 109 % xmllint --version
xmllint: using libxml version 20913
   compiled with: Threads Tree Output Push Reader Patterns Writer SAXv1 FTP HTTP DTDValid HTML Legacy C14N Catalog XPath XPointer XInclude ICU ISO8859X Unicode Regexps Automata Schemas Schematron Modules Debug Zlib 
gapinski@flexion-mac-C02FCBVSMD6N 109 % time xmllint --noout --schema ~/Projects/github/usnistgov/OSCAL/xml/schema/oscal_complete_schema.xsd AwesomeCloudSSP1.xml
AwesomeCloudSSP1.xml validates
xmllint --noout --schema  AwesomeCloudSSP1.xml  0.05s user 0.01s system 94% cpu 0.056 total
gapinski@flexion-mac-C02FCBVSMD6N 109 %
```

**Comment by GaryGapinski** [comment]
I found some additional surprises.

If one validates [this sample system-security-plan](https://github.com/GaryGapinski/OSCAL/blob/refactoring/extra/refactoring/manipulate-uuid/sample.xml) using [branch `v1.0.4` `oscal_complete_schema.xsd`](https://raw.githubusercontent.com/usnistgov/OSCAL/v1.0.4/xml/schema/oscal_complete_schema.xsd) or [branch `main` `oscal_complete_schema.xsd`](https://raw.githubusercontent.com/usnistgov/OSCAL/main/xml/schema/oscal_complete_schema.xsd) validation is successful — empty `description` elements are correct.

If the schema is obtained from the [branch `develop` `oscal_complete_schema.xsd`](https://raw.githubusercontent.com/usnistgov/OSCAL/develop/xml/schema/oscal_complete_schema.xsd), validation errors appear.
```
gapinski@flexion-mac-C02FCBVSMD6N manipulate-uuid % curl --silent -o oscal_complete_schema.xsd https://raw.githubusercontent.com/usnistgov/OSCAL/develop/xml/schema/oscal_complete_schema.xsd
gapinski@flexion-mac-C02FCBVSMD6N manipulate-uuid % xmllint --noout --schema oscal_complete_schema.xsd sample.xml                                                                            
sample.xml:15: element description: Schemas validity error : Element '{http://csrc.nist.gov/ns/oscal/1.0}description': Missing child element(s). Expected is one of ( {http://csrc.nist.gov/ns/oscal/1.0}h1, {http://csrc.nist.gov/ns/oscal/1.0}h2, {http://csrc.nist.gov/ns/oscal/1.0}h3, {http://csrc.nist.gov/ns/oscal/1.0}h4, {http://csrc.nist.gov/ns/oscal/1.0}h5, {http://csrc.nist.gov/ns/oscal/1.0}h6, {http://csrc.nist.gov/ns/oscal/1.0}p, {http://csrc.nist.gov/ns/oscal/1.0}ul, {http://csrc.nist.gov/ns/oscal/1.0}ol, {http://csrc.nist.gov/ns/oscal/1.0}pre ).
sample.xml:20: element description: Schemas validity error : Element '{http://csrc.nist.gov/ns/oscal/1.0}description': Missing child element(s). Expected is one of ( {http://csrc.nist.gov/ns/oscal/1.0}h1, {http://csrc.nist.gov/ns/oscal/1.0}h2, {http://csrc.nist.gov/ns/oscal/1.0}h3, {http://csrc.nist.gov/ns/oscal/1.0}h4, {http://csrc.nist.gov/ns/oscal/1.0}h5, {http://csrc.nist.gov/ns/oscal/1.0}h6, {http://csrc.nist.gov/ns/oscal/1.0}p, {http://csrc.nist.gov/ns/oscal/1.0}ul, {http://csrc.nist.gov/ns/oscal/1.0}ol, {http://csrc.nist.gov/ns/oscal/1.0}pre ).
sample.xml:39: element description: Schemas validity error : Element '{http://csrc.nist.gov/ns/oscal/1.0}description': Missing child element(s). Expected is one of ( {http://csrc.nist.gov/ns/oscal/1.0}h1, {http://csrc.nist.gov/ns/oscal/1.0}h2, {http://csrc.nist.gov/ns/oscal/1.0}h3, {http://csrc.nist.gov/ns/oscal/1.0}h4, {http://csrc.nist.gov/ns/oscal/1.0}h5, {http://csrc.nist.gov/ns/oscal/1.0}h6, {http://csrc.nist.gov/ns/oscal/1.0}p, {http://csrc.nist.gov/ns/oscal/1.0}ul, {http://csrc.nist.gov/ns/oscal/1.0}ol, {http://csrc.nist.gov/ns/oscal/1.0}pre ).
sample.xml:46: element description: Schemas validity error : Element '{http://csrc.nist.gov/ns/oscal/1.0}description': Missing child element(s). Expected is one of ( {http://csrc.nist.gov/ns/oscal/1.0}h1, {http://csrc.nist.gov/ns/oscal/1.0}h2, {http://csrc.nist.gov/ns/oscal/1.0}h3, {http://csrc.nist.gov/ns/oscal/1.0}h4, {http://csrc.nist.gov/ns/oscal/1.0}h5, {http://csrc.nist.gov/ns/oscal/1.0}h6, {http://csrc.nist.gov/ns/oscal/1.0}p, {http://csrc.nist.gov/ns/oscal/1.0}ul, {http://csrc.nist.gov/ns/oscal/1.0}ol, {http://csrc.nist.gov/ns/oscal/1.0}pre ).
sample.xml:51: element description: Schemas validity error : Element '{http://csrc.nist.gov/ns/oscal/1.0}description': Missing child element(s). Expected is one of ( {http://csrc.nist.gov/ns/oscal/1.0}h1, {http://csrc.nist.gov/ns/oscal/1.0}h2, {http://csrc.nist.gov/ns/oscal/1.0}h3, {http://csrc.nist.gov/ns/oscal/1.0}h4, {http://csrc.nist.gov/ns/oscal/1.0}h5, {http://csrc.nist.gov/ns/oscal/1.0}h6, {http://csrc.nist.gov/ns/oscal/1.0}p, {http://csrc.nist.gov/ns/oscal/1.0}ul, {http://csrc.nist.gov/ns/oscal/1.0}ol, {http://csrc.nist.gov/ns/oscal/1.0}pre ).
sample.xml:52: element implemented-requirement: Schemas validity error : Element '{http://csrc.nist.gov/ns/oscal/1.0}implemented-requirement', attribute 'control-id': [facet 'pattern'] The value '…' is not accepted by the pattern '(\p{L}|_)(\p{L}|\p{N}|[.\-_])*'.
sample.xml:53: element statement: Schemas validity error : Element '{http://csrc.nist.gov/ns/oscal/1.0}statement', attribute 'statement-id': [facet 'pattern'] The value '…' is not accepted by the pattern '(\p{L}|_)(\p{L}|\p{N}|[.\-_])*'.
sample.xml fails to validate
gapinski@flexion-mac-C02FCBVSMD6N manipulate-uuid % 
```
Note that [`TokenDatatype`](https://github.com/usnistgov/OSCAL/blob/develop/xml/schema/oscal_complete_schema.xsd#L8827-L8846) is novel in the `develop` branch.

`<description>` can no longer be void but `<description ><p></p></description>` is valid for those who value terse descriptions. Contrast `main` [`blockElementGroup`](https://github.com/usnistgov/OSCAL/blob/main/xml/schema/oscal_complete_schema.xsd#L8446-L8461) with `develop` [`blockElementGroup`](https://github.com/usnistgov/OSCAL/blob/develop/xml/schema/oscal_complete_schema.xsd#L8612-L8627).

These schema changes are apparently "breaking" changes.

I tried rebuilding `oscal-cli` from its `main` (`oscal-cli version 0.3.2 built on 2023-03-04 11:32 on commit d652eac`) branch but that looks like it might be using the OSCAL `develop` branch and thus has erroneous validation errors.

**Comment by aj-stein-nist** [comment]
Some more investigation is needed around how the different XML Schema engines, cited here and those that are in use by the community, do not appear to be handling `<description></description>` and `<description />` consistently based on testing. More to follow.

**Comment by wendellpiez** [comment]
Random observations:

In a conformant XML parser, the notations `<description></description>`, `<description/>` and `<description />` are all functionally equivalent. The two latter forms follow the production [44](https://www.w3.org/TR/REC-xml/#sec-starttags), which stipulates specifically

> Empty-element tags may be used for any element which has no content, whether or not it is declared using the keyword EMPTY.

In the OSCAL case, an empty `description` element is one that happens to have no content, not declared as EMPTY (which is valid as long as content is optional).

A conformant XML parser will also make no distinction between `<description/>` and `<description />` - the practice of using a space has evolved specifically as a workaround to non-XML parsers (HTML parsers) seeing an element named "br/" instead of "br" for the `<br/>` notation. As an alternative to this, more robust solutions to this problem include (in either XML or HTML contexts)

- `<br class="br"/>
- `<br></br>

... although some HTML processors will see two `br` elements in the second case, not one.

**Comment by GaryGapinski** [comment]
There should probably be a deficient XML parser blacklist. However, someone at some point on the OSCAL develop branch fiddled with the `description` substructure by **requiring** substructure — not just any substructure, but a faux HTML substructure.

**Comment by wendellpiez** [comment]
Indeed, this is in keeping with the (untestable) proposition that "every description should say something".

**Comment by david-waltermire-nist** [comment]
The [`markup-multiline`]( https://pages.nist.gov/OSCAL/reference/datatypes/#markup-multiline) data type requires use of top-level block elements i.e. `h1`, `p`, etc. This is enforced in the v1.04 schemas. The older schemas had bugs preventing proper validation.

It's also important to recognize that the markup in OSCAL XML is XML, not HTML. Although it is HTML-like, it must be valid XML.

I don't have anything new to say about the untestable proposition that "every description should say something". There is no way to win that war.

**Comment by aj-stein-nist** [comment]
It seems I need to adjust this to focus on how to opt-in or opt-out of stack trace output, as the error messages seem clear given the schema violations, just different engines are handling things in an inconsistent way (and perhaps in a way non-conformant with the XML spec in some cases).

Re the war on descriptions that must say something, it would appear that downstream developers of tools and OSCAL content only could feel the need to put in a description that says nothing, invalid or not, because the schema requires them to be positioned in certain places. As that is an OSCAL concern, I strongly recommend you provide additional feedback on https://github.com/usnistgov/OSCAL/issues/1725 or open up relevant issues on where you recommend the description itself ought not be required.

**Comment by wendellpiez** [comment]
To add to what Dave says, there are cases where markup-multiline appears such as control/part, unwrapped in sequence with other elements, such that it has the effect of being optional (parts are still valid without markup-multiline-something), not because markup-multiline does not require an element but because the (unwrapped) group itself is optional.

This is stricter than it was, but in a good way.

Making `description` itself optional would be a "solution" to "requiring the noise". Unless we feel the noise is information (back to DW point about wars that will never be won). My take on whether it's (always/ever) a good idea to require `description` depends in part on the context, i.e. the element where the description appears (e.g. does it already require a `title` or other element)?

FWIW I can't tell from the stack trace whether the parsing issues are even related to the reported validation error.
