### ISSUE TITLE
Validation of by-component cardinality question

### ISSUE THREAD

**Issue by volpet2014** [usnistgov/oscal-cli#74]
{Please enter your question.}
When running validation on a JSON SSP,  multiple validation errors are reported for by-component that states -  [ERROR] [/system-security-plan/control-implementation[1]/implemented-requirement[1]] The cardinality '0' is below the required minimum '1' for items matching the expression './/by-component'.  **NOTE: The JSON SSP in question contains no by-component references**.  

The  system-security-plan/ json-outline shows cardinality of  [0 or 1] which I read as it is not a required at the implemented-requirement level.    Which is correct?  Or am I mis-interpreting? 
[by-components](https://pages.nist.gov/OSCAL/reference/latest/system-security-plan/json-reference/#/system-security-plan/control-implementation/implemented-requirements/by-components) [0 or 1]?
[SampleSSP_oscal_cli_validation_output.txt](https://github.com/usnistgov/oscal-cli/files/9965082/SampleSSP_oscal_cli_validation_output.txt)

**Comment by aj-stein-nist** [comment]
Hi, @volpet2014. 👋 Can you confirm this bug is reproducible with [the 0.3.1 release](https://search.maven.org/search?q=g:gov.nist.secauto.oscal.tools.oscal-cli%20AND%20v:0.3.1) and verify this bug? Thanks again for formally reporting, I will build a quick example SSP and verify the bug and work with the team to get this triaged.

**Comment by aj-stein-nist** [comment]
Also can you please confirm the numbers of components in the SSP, is there `this-system` component in the SSP generally or is there not, @volpet2014? I want to recteate two examples to confirm the error messages appear when we think they ought to.

**Comment by openprivacy** [comment]
If there is a `by-components` (with an `s`) then there must be at least one [1 to ∞] `by-component` entry

**Comment by aj-stein-nist** [comment]
> If there is a `by-components` (with an `s`) then there must be at least one [1 to ∞] `by-component` entry

In the array (for JSON), but for an `implemented-requirement` or at the `statement` level, but at either level in the SSP (control or statement), the cardinality is 0 or 1 because it is beyond what can be enforced naively by JSON or XML Schema: which one you may have is dependent on how specific you are being, and the schema cannot target this `by-component` or the other with that level specificity in JSON schema.

Does that make sense?

**Comment by aj-stein-nist** [comment]
And to clarify since both of you are technically right: the `oscal-cli` is not reporting an error based upon the strict requirements of the XML Schema, but a constraint (this is from `v1.0.4` release):

https://github.com/usnistgov/OSCAL/blob/v1.0.4/src/metaschema/oscal_ssp_metaschema.xml#L745-L749

Due to the beauty and mystery of XPath, `//by-component` query that drives the validation and guides `oscal-cli` operation applies to the `implemented-requirement` and nested `statement` level.

**Comment by volpet2014** [comment]
Thanks for the clarifications.    The net is you must have at least 1 by-component at the control or statement level for this to pass validations.  Correct?   The JSON outline was confusing to me when I looked at it.

**Comment by aj-stein-nist** [comment]
> The net is you must have at least 1 by-component at the control or statement level for this to pass validations. Correct?

Yes.

> The JSON outline was confusing to me when I looked at it.

There are limits to what purely JSON Schema can tell you here. So the schema allows it but because it cannot be stricter, but it would not logically be very useful. One of the key benefits of the `oscal-cli` over purely using JSON Schema is this kind of detection and analysis.

Thanks so much for reporting. I am sorry I needed so much detail to understand the specific issue, and that is expected behavior for now. Feel free to reopen if things are unclear and you expected different behavior or an improvement.
